version: "3"
services:
  ganache:
    image: blockchainfranklin/ganache:1.0.0
    build:
      context: ./ganache
      dockerfile: Dockerfile.ganache
    ports:
      - "8545:8545"
  react:
    image: blockchainfranklin/frontend:1.0.0
    build: ./client
    ports:
      - "80:3000"
